<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VehicleSeeder extends Seeder
{
    public function run(): void
    {
        \DB::statement('SET FOREIGN_KEY_CHECKS=0;');
    \DB::table('vehicles')->truncate();
    \DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        \DB::table('vehicles')->insert([
            [
                'brand' => 'Toyota',
                'model' => 'Corolla',
                'fuel_type' => 'Petrol',
                'fuel_efficiency' => '15 km/l',
                'year' => 2020,
                'color' => 'White',
                'image_1' => 'https://images.dealer.com/ddc/vehicles/2025/Toyota/Corolla/Sedan/trim_LE_c8e3ad/color/Ice%20Cap-040-251%2C250%2C248-640-en_US.jpg?impolicy=resize&w=640',
                'seats' => 5,
                'engine' => '1.8L',
                'registration_number' => 'ABC12334',
                'mileage' => 35000,
                'daily_rate' => 45.99,
                'is_available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand' => 'Honda',
                'model' => 'Civic',
                'fuel_type' => 'Diesel',
                'fuel_efficiency' => '17 km/l',
                'year' => 2019,
                'color' => 'Black',
                'image_1' => 'https://automobiles.honda.com/-/media/Honda-Automobiles/Vehicles/2025/civic-sedan/non-VLP/10-Family/MY25_Civic_Family_Card_Jelly_2x.png?sc_lang=en',
                'seats' => 5,
                'engine' => '2.0L',
                'registration_number' => 'XYZ56378',
                'mileage' => 42000,
                'daily_rate' => 49.99,
                'is_available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand' => 'Nissan',
                'model' => 'X-Trail',
                'fuel_type' => 'Hybrid',
                'fuel_efficiency' => '13 km/l',
                'year' => 2021,
                'color' => 'Silver',
                'image_1' => 'https://m.atcdn.co.uk/vms/media/b68a9b0f74c14372b376acc4ca35c639.jpg',
                'seats' => 7,
                'engine' => '2.5L',
                'registration_number' => 'JKL34356',
                'mileage' => 27000,
                'daily_rate' => 60.00,
                'is_available' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand' => 'Ford',
                'model' => 'Focus',
                'fuel_type' => 'Petrol',
                'fuel_efficiency' => '14 km/l',
                'year' => 2018,
                'color' => 'Blue',
                'image_1' => 'https://images.hgmsites.net/med/2018-ford-focus-titanium-sedan-angular-front-exterior-view_100644242_m.jpg',
                'seats' => 5,
                'engine' => '1.6L',
                'registration_number' => 'LMN78390',
                'mileage' => 50000,
                'daily_rate' => 39.50,
                'is_available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand' => 'Nissan',
                'model' => 'Altima',
                'fuel_type' => 'Petrol',
                'fuel_efficiency' => '16 km/l',
                'year' => 2021,
                'color' => 'Red',
                'image_1' => 'https://www.bedfordnissan.com/blogs/1502/wp-content/uploads/2020/07/2020_Nissan_Altima_S.png',
                'seats' => 5,
                'engine' => '2.5L',
                'registration_number' => 'NIS9087',
                'mileage' => 30000,
                'daily_rate' => 55.50,
                'is_available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand' => 'Hyundai',
                'model' => 'Elantra',
                'fuel_type' => 'Diesel',
                'fuel_efficiency' => '18 km/l',
                'year' => 2022,
                'color' => 'Grey',
                'image_1' => 'https://cache2.pakwheels.com/system/car_generation_pictures/7778/original/Front_Left_View.jpg?1729860896',
                'seats' => 5,
                'engine' => '1.6L',
                'registration_number' => 'HYU3321',
                'mileage' => 15000,
                'daily_rate' => 60.00,
                'is_available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand' => 'BMW',
                'model' => '320i',
                'fuel_type' => 'Petrol',
                'fuel_efficiency' => '13 km/l',
                'year' => 2017,
                'color' => 'Black',
                'image_1' => 'https://www.bmw.co.za/content/dam/bmw/marketZA/bmw_co_za/images/bmw-finance/select-offers/bmw-3-series-sedan-320i-lci-offer-cosy-image.png',
                'seats' => 5,
                'engine' => '2.0L TwinPower Turbo',
                'registration_number' => 'BMW3320',
                'mileage' => 60000,
                'daily_rate' => 90.00,
                'is_available' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
